# Generated by Django 4.2.2 on 2023-07-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='user',
            new_name='email',
        ),
    ]
