# Generated by Django 4.2.2 on 2023-07-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_rename_email_asignacion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCiclo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numCreditos', models.IntegerField()),
                ('numHoras', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_carrera', to='calendarapp.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='CarreraCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_c', to='calendarapp.carrera')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_m', to='calendarapp.ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_carrera', to='calendarapp.carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_ciclo', to='calendarapp.ciclo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_materia', to='calendarapp.materia'),
            preserve_default=False,
        ),
    ]
