# Generated by Django 4.2.2 on 2023-07-23 22:42

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_asignacion_descripcion_asignacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_final',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
