# Generated by Django 4.2.2 on 2023-07-23 22:52

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_alter_asignacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_final',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
