# Generated by Django 4.2.2 on 2023-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_alter_asignacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
