# Generated by Django 4.2.2 on 2023-07-23 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_alter_asignacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_inicial',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_final',
            field=models.DateTimeField(),
        ),
    ]
