# Generated by Django 4.2.2 on 2023-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_remove_asignacion_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_materia', to='calendarapp.materia'),
        ),
    ]
