# Generated by Django 4.2.2 on 2023-07-26 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0018_archivos_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='asignacion',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='archivo_asignacion', to='calendarapp.asignacion'),
            preserve_default=False,
        ),
    ]
